spring:
  influxdb:
    url: http://10.0.1.191:8086
    username: user
    password: ~
    database: mydb
    retention-policy: autogen
    //connect-timeout: 10
    //read-timeout: 30
    //write-timeout: 10
    //gzip: true